#include "dialogs\identity_card_civilian.hpp"
#include "dialogs\identity_card_others.hpp"
#include "dialogs\identity_permis.hpp"
#include "dialogs\identity_card_medic.hpp"
#include "dialogs\identity_card_police.hpp"